FROM php:8.3-apache

# Install vi, nano, and MySQL extensions
RUN apt-get update && apt-get install -y \
    vim \
    nano \
    libpq-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    && docker-php-ext-install mysqli pdo pdo_mysql \
    && rm -rf /var/lib/apt/lists/* \
    && composer2 require tecnickcom/tcpdf \
    && composer2 require endroid/qr-code \
    && composer2 require phpmailer/phpmailer




